#!/bin/bash -li
set -o errexit
source $HEDGEYE_UTILITIES_PATH/set_up_rvm
mkdir -p temp/pids
git checkout master
git pull origin master
bundle install
bundle exec rake ci
# /bin/bash --login -- ~/work/yard_use/generate_ruby19_docs.shecho '*** starting Billing-Logic build ***' &>/dev/stderr
